owner_comment_categories:
  type: list
  list_type: category
  default: ""
  description: "Categories where topics will auto-filter to show only the topic owner's posts"

owner_comment_prefetch:
  type: integer
  default: 3
  min: 0
  max: 10
  description: "Number of replies to automatically expand under each owner post (0-10)"
