owner_comment_categories:
  type: list
  list_type: category
  default: ""
  description: "Categories where topics will auto-filter to show only the topic owner's posts"


auto_mode:
  type: bool
  default: true
  description: "Automatically enable owner-only filtered view in enabled categories"


# Toggle button to switch between regular and owner-filtered views
toggle_view_button_enabled:
  type: bool
  default: true
  description: "Enable/disable the toggle view button"


# Group-based access control settings


allowed_groups:
  type: list
  list_type: group
  default: ""
  description: "Select groups that are allowed to access this theme component's features"


behavior_for_anonymous:
  type: enum
  default: deny
  choices:
    - deny
    - allow
  description: "Deprecated: no longer used; access depends solely on Allowed groups (empty = everyone)"


# Reply button visibility control

hide_reply_buttons_for_non_owners:
  type: bool
  default: false
  description: "Hide reply buttons on posts authored by non-owners in configured Owner comment categories. Applies in both filtered and regular topic views. Does not check Allowed groups. This is a UI-only restriction and does not prevent replies via keyboard shortcuts or API calls."

