owner_comment_categories:
  type: list
  list_type: category
  default: ""
  description: "Categories where topics will auto-filter to show only the topic owner's posts"


auto_mode:
  type: bool
  default: true
  description: "Automatically enable owner-only filtered view in enabled categories"


# Toggle button to switch between regular and owner-filtered views
toggle_view_button_enabled:
  type: bool
  default: true
  description: "Enable/disable the toggle view button"


# Group-based access control settings
group_access_enabled:
  type: bool
  default: false
  description: "Enable group-based access control for this theme component"


include_staff:
  type: bool
  default: true
  description: "Allow staff members to access the theme component regardless of group membership"


allowed_groups:
  type: list
  list_type: group
  default: ""
  description: "Select groups that are allowed to access this theme component's features"


behavior_for_anonymous:
  type: enum
  default: deny
  choices:
    - deny
    - allow
  description: "How to handle anonymous (logged-out) users"

