owner_comment_categories:
  type: list
  list_type: category
  default: ""
  description: "Categories where topics will auto-filter to show only the topic owner's posts"


auto_mode:
  type: bool
  default: true
  description: "Automatically enable owner-only filtered view in enabled categories"


# Toggle button to switch between regular and owner-filtered views
toggle_view_button_enabled:
  type: bool
  default: true
  description: "Enable/disable the toggle view button"

toggle_label_unfiltered:
  type: text
  default: "Thema"
  description: "Button label when topic is in regular (unfiltered) view"

toggle_label_filtered:
  type: text
  default: "Growreport"
  description: "Button label when topic is in filtered (owner-only) view"
